<% from "build.inc.yml" import workflow, workflow_dispatch -%>
name: Build Test and Publish Nightly Packages

on:
  schedule:
    - cron: "0 1 * * *"
  <<- workflow_dispatch() >>
  push:
    branches:
      - nightly

jobs:
  <<- workflow(package, targets, publications, subdist="nightly") ->>
