<% from "build.inc.yml" import workflow, workflow_dispatch -%>
name: Build Test and Publish a Release

on:
  <<- workflow_dispatch() >>

jobs:
  <<- workflow(package, targets, publications, subdist="", publish_all=True) ->>
