blank_issues_enabled: false
contact_links:
  - name: Problem with Gel UI
    url: https://github.com/geldata/gel-ui/issues
    about: If you've found a bug or have a feature request for Gel UI, please open an issue in the gel-ui repo.
  - name: Long question or idea
    url: https://github.com/geldata/gel/discussions
    about: Ask long-form questions and discuss ideas.
  - name: Quick questions or chat
    url: https://www.geldata.com/p/discord
    about: Ask quick questions or simply chat on the Gel Discord server.
