name: Deploy Documentation Changes

on:
  push:
    branches:
      - master
      - release/**
    paths:
      - "docs/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger vercel deploy hook
        run: curl \
          --fail-with-body \
          --request POST \
          ${{ secrets.VERCEL_DOC_DEPLOY_URL_HOOK }}
